# Site settings
title: Matt Jones' UT Blog 
email: matthew.p.jones@mba16.mccombs.utexas.edu
description: "Check-ins from a first year MBA student"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: mattpauljones
github_username:  jonesyguy3
linkedin_username: matthewpauljones

# Build settings
markdown: kramdown
permalink: pretty
